# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 54f7de871a6485299fe03ad2c76f5e5be1a1ee7074b76c7af32d35240b2f2cb590df770f1974f02220500ce4d85761f87db5ba1c1a687f662cf5a370ce8482af

test:
  secret_key_base: 6366eaba21ffcf7c1828cdd4ffdb051b076ada6c4601608bc35d8562f1434f45cc85a3e605a342d34ff88061ea6fa598bd6b04604e94934361ad4f1914d6b1b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
